language: ruby
cache: bundler

rvm:
  - ruby
  - 2.1.2
  - 2.2.2

script: bundle exec rspec

notifications:
  email:
    recipients:
      - knx@digitalheads.pl
    on_failure: change
    on_success: never
